[package]
name = "cliff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencl3 = {version = "0.9.3"}
thiserror = {version = "1.0.50"}
gcd = {version = "*"}
